version: "3"

services:
  web:
    image: kevinkao/apache-php7-fpm
    volumes:
      - .:/var/www/html/public
    tty: true
    depends_on:
      - db
    ports:
      - "8080:80"

  db:
    image: mariadb:10.2
    ports:
      - 33068:3306
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password